package com.qiumi.app.support.common.upload;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import java.io.Serializable;

/**
 * Entity mapped to table "UPLOAD_ENTITY".
 */
public class UploadEntity implements Serializable {

    private Long id;
    private String uuid;
    private String url;
    private String localFile;
    private String fileName;
    private Long fileTotalSize;
    private Long uploadSize;
    private Long startTime;
    private Long operTime;
    private Integer state;
    private String fileID;
    private Boolean isContinue;

    private Integer progress;

    public UploadEntity() {
    }

    public UploadEntity(Long id) {
        this.id = id;
    }

    public UploadEntity(Long id, String uuid, String url, String localFile, String fileName, Long fileTotalSize, Long uploadSize, Long startTime, Long operTime, Integer state, String fileID, Boolean isContinue) {
        this.id = id;
        this.uuid = uuid;
        this.url = url;
        this.localFile = localFile;
        this.fileName = fileName;
        this.fileTotalSize = fileTotalSize;
        this.uploadSize = uploadSize;
        this.startTime = startTime;
        this.operTime = operTime;
        this.state = state;
        this.fileID = fileID;
        this.isContinue = isContinue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getLocalFile() {
        return localFile;
    }

    public void setLocalFile(String localFile) {
        this.localFile = localFile;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getFileTotalSize() {
        return fileTotalSize;
    }

    public void setFileTotalSize(Long fileTotalSize) {
        this.fileTotalSize = fileTotalSize;
    }

    public Long getUploadSize() {
        return uploadSize;
    }

    public void setUploadSize(Long uploadSize) {
        this.uploadSize = uploadSize;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getOperTime() {
        return operTime;
    }

    public void setOperTime(Long operTime) {
        this.operTime = operTime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getFileID() {
        return fileID;
    }

    public void setFileID(String fileID) {
        this.fileID = fileID;
    }

    public Boolean getIsContinue() {
        return isContinue;
    }

    public void setIsContinue(Boolean isContinue) {
        this.isContinue = isContinue;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }
}
